{"name": "Ошибка: неверный id заказа", "status": "passed", "start": 1761069052097, "stop": 1761069052346, "uuid": "18c13a18-1c38-4b48-9212-d1fcac37677c", "historyId": "865015221c7d0ef3efbc96b991487ceb", "testCaseId": "865015221c7d0ef3efbc96b991487ceb", "fullName": "tests.test_order_accept.TestAcceptOrder#test_accept_order_with_invalid_order_id_fails", "labels": [{"name": "feature", "value": "Order API"}, {"name": "story", "value": "Принятие заказа (Назначение курьера)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "5476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}], "titlePath": ["tests", "test_order_accept.py", "TestAcceptOrder"]}