{"name": "Ошибка при неверных логине/пароле", "status": "passed", "start": 1761069039994, "stop": 1761069040241, "uuid": "fae615c7-0ab5-4eba-a2e9-e9d7d4a952d9", "historyId": "4221f6fbea916974d6b34f6cb6b56823", "testCaseId": "4221f6fbea916974d6b34f6cb6b56823", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_with_wrong_credentials_fails", "labels": [{"name": "feature", "value": "API Courier"}, {"name": "story", "value": "Авторизация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "5476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}], "titlePath": ["tests", "test_courier_login.py", "TestCourierLogin"]}